### ISSUE TITLE
About the training data

### ISSUE THREAD

**Issue by acharkq** [rxn4chemistry/smiles2actions#2]
Hi Authors,

Thanks for the great work on smiles 2 action prediction. I have a question regarding the training dataset. 

Does the training data include those annotated by human experts in another work of your group 'Automated extraction of chemical synthesis actions from experimental procedures'. 

I have read through your paper, and do not find a hint of using any human-annotated data. 

If my observation is correct, would you elaborate on the reason?

Thanks for the help!!

**Comment by avaucher** [comment]
Hi,
No, it does not include the annotations from the other work - these were sentence-based and did not refer to any chemical eqiation. Indeed, there is no human-annotated data in smiles2actions. This would be feasible but may require quite a lot of work.
